[project]
name = "pycreative"
version = "0.1.0"
description = "Batteries-included creative coding framework for Python, built atop PyGame."
authors = [{name = "Pete Haughie", email = "pete@example.com"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "pygame",
    "skia-python",
    "pillow",
    "numpy",
    "PyOpenGL",
    "opencv-python",
]

[optional-dependencies]
audio = ["sounddevice"]
video = ["ffmpeg-python", "opencv-python"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
package-dir = {"" = "src"}

[project.scripts]
pycreative = "pycreative.cli:main"
